-- MySQL Script generated by MySQL Workbench
-- lun. 12 oct. 2020 11:17:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JobBoard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JobBoard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JobBoard` ;
USE `JobBoard` ;

-- -----------------------------------------------------
-- Table `JobBoard`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JobBoard`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL DEFAULT NULL,
  `prenom` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `user` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = REDUNDANT;


-- -----------------------------------------------------
-- Table `JobBoard`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JobBoard`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ceoUserId` INT NOT NULL,
  PRIMARY KEY (`id`, `ceoUserId`),
  INDEX `fk_companies_user1_idx` (`ceoUserId` ASC) VISIBLE,
  CONSTRAINT `fk_companies_user1`
    FOREIGN KEY (`ceoUserId`)
    REFERENCES `JobBoard`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `JobBoard`.`ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JobBoard`.`ads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companiesId` INT NOT NULL,
  `ownerUserId` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `Description` VARCHAR(255) CHARACTER SET 'armscii8' NOT NULL,
  `wage` INT NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `hours` INT NOT NULL,
  PRIMARY KEY (`id`, `ownerUserId`, `title`, `Description`, `wage`, `location`, `hours`, `companiesId`),
  INDEX `fk_ads_companies1_idx` (`companiesId` ASC) VISIBLE,
  INDEX `fk_ads_user1_idx` (`ownerUserId` ASC) VISIBLE,
  CONSTRAINT `fk_ads_companies1`
    FOREIGN KEY (`companiesId`)
    REFERENCES `JobBoard`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ads_user1`
    FOREIGN KEY (`ownerUserId`)
    REFERENCES `JobBoard`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `JobBoard`.`jobApplication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JobBoard`.`jobApplication` (
  `id` INT NOT NULL,
  `adsId` INT NOT NULL,
  PRIMARY KEY (`id`, `adsId`),
  INDEX `fk_jobApplication_ads1_idx` (`adsId` ASC) VISIBLE,
  CONSTRAINT `fk_jobApplication_ads1`
    FOREIGN KEY (`adsId`)
    REFERENCES `JobBoard`.`ads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `JobBoard`.`administrateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JobBoard`.`administrateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_administrateur_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `JobBoard`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `JobBoard`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `JobBoard`;
INSERT INTO `JobBoard`.`user` (`id`, `nom`, `prenom`, `email`, `user`, `password`, `phone`) VALUES (1, 'test1', 'test1', 'test1@test1.test1', 'test1', 'test1', 0760790840);

COMMIT;


-- -----------------------------------------------------
-- Data for table `JobBoard`.`companies`
-- -----------------------------------------------------
START TRANSACTION;
USE `JobBoard`;
INSERT INTO `JobBoard`.`companies` (`id`, `name`, `ceoUserId`) VALUES (1, 'google', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `JobBoard`.`ads`
-- -----------------------------------------------------
START TRANSACTION;
USE `JobBoard`;
INSERT INTO `JobBoard`.`ads` (`id`, `companiesId`, `ownerUserId`, `title`, `Description`, `wage`, `location`, `hours`) VALUES (1, 1, 1, 'DevOps', 'Recherche devOps bac+9', 4000, 'Montpellier', 5);

COMMIT;

