name: Is Symfony working ?

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2
        
      - name: install composer
        run : |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '795f976fe0ebd8b75f26a6dd68f78fd3453ce79f32ecb33e7fd087d39bfeb978342fb73ac986cd4f54edd0dc902601dc') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
        
      - name: install var and vendor
        run: |
          cd symfony
          composer install

      - name: start Symfony server
        run: |
          cd symfony
          php -S localhost:8000 -t public &
